Repository go-vela/server, pull requests merged in 2019-11, with the labels that each got.

#7 Add readme badges
  .github/README.md
Labels: enhancement

#8 Fix path to repo for docker.io
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: bug

#9 Update go-vela/compiler for git plugin rename
  go.mod
  go.sum
Labels: enhancement

#10 Use goveralls to report test coverage to coveralls
  .github/workflows/test.yml
Labels: enhancement

#11 Set proper version for Vela
  router/middleware/header_test.go
  version/version.go
Labels: bug

#12 Upgrade Vela dependencies for login bug
  go.mod
  go.sum
Labels: bug

#13 Refactor to improve Go Report Card
  api/webhook.go
  database/init_cgo.go
  database/service_test.go
  secret/vault/list_test.go
  source/github/repo_test.go
  util/util.go
Labels: enhancement

#15 Update go mod
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: enhancement

#17 Update compiler for hardcoded environment variables
  go.mod
  go.sum
Labels: bug

#18 Fix bug in capturing full secret path
  api/secret.go
  router/middleware/header_test.go
  router/middleware/service/service.go
  router/middleware/step/step.go
  router/secret.go
  version/version.go
Labels: bug

#19 Adopt official mattn/goveralls integration
  .github/workflows/test.yml
Labels: enhancement

#20 Fix database calls to capture logs
  api/log.go
Labels: bug

#21 Update go-vela/types for Repo field rename
  database/ddl/postgres/secret.go
  database/ddl/sqlite/secret.go
  database/secret_test.go
  go.mod
  go.sum
  secret/native/create_test.go
  secret/native/get_test.go
  secret/native/list_test.go
  secret/native/update_test.go
Labels: bug

#22 Update version for release
  router/middleware/header_test.go
  version/version.go
Labels: bug

#23 Update go-vela dependencies for bug fixes
  go.mod
  go.sum
Labels: bug

#24 refactor(api): use setters for library types
  api/authentication.go
  api/build.go
  api/log.go
  api/repo.go
  api/secret.go
  api/service.go
  api/step.go
  api/user.go
  api/webhook.go
Labels: enhancement

#25 refactor(database): use setters for library types
  database/build_test.go
  database/log_test.go
  database/repo_test.go
  database/secret_test.go
  database/service_test.go
  database/step_test.go
  database/user_test.go
  go.mod
Labels: enhancement

#26 refactor(router): use setters for library types
  router/middleware/build/build_test.go
  router/middleware/logger_test.go
  router/middleware/perm/perm_test.go
  router/middleware/repo/repo_test.go
  router/middleware/service/service_test.go
  router/middleware/step/step_test.go
  router/middleware/token/token.go
  router/middleware/token/token_test.go
  router/middleware/user/user.go
  router/middleware/user/user_test.go
Labels: enhancement

#27 refactor(secret): use setters for library types
  secret/native/count_test.go
  secret/native/create_test.go
  secret/native/delete_test.go
  secret/native/get_test.go
  secret/native/list_test.go
  secret/native/update.go
  secret/native/update_test.go
  secret/vault/create_test.go
  secret/vault/get_test.go
  secret/vault/list_test.go
  secret/vault/testdata/org.json
  secret/vault/update_test.go
  secret/vault/vault.go
Labels: enhancement

#28 refactor(source): use setters for library types
  source/github/access_test.go
  source/github/authentication_test.go
  source/github/repo_test.go
  source/github/webhook.go
  source/github/webhook_test.go
Labels: enhancement

#30 Add DML for webhook transaction log
  database/dml/dml.go
  database/dml/dml_test.go
  database/dml/postgres.go
  database/dml/postgres/hook.go
  database/dml/postgres/hook_test.go
  database/dml/postgres/postgres.go
  database/dml/postgres/postgres_test.go
  database/dml/postgres_test.go
  database/dml/sqlite.go
  database/dml/sqlite/hook.go
  database/dml/sqlite/hook_test.go
  database/dml/sqlite/sqlite.go
  database/dml/sqlite/sqlite_test.go
  database/dml/sqlite_test.go
Labels: feature

#29 Add DDL for webhook transaction log
  database/ddl/ddl.go
  database/ddl/ddl_test.go
  database/ddl/postgres.go
  database/ddl/postgres/hook.go
  database/ddl/postgres/hook_test.go
  database/ddl/postgres/postgres.go
  database/ddl/postgres/postgres_test.go
  database/ddl/postgres_test.go
  database/ddl/sqlite.go
  database/ddl/sqlite/hook.go
  database/ddl/sqlite/hook_test.go
  database/ddl/sqlite/sqlite.go
  database/ddl/sqlite/sqlite_test.go
  database/ddl/sqlite_test.go
Labels: feature

#32 Fix(step): plan steps should set step id not service
  api/step.go
Labels: bug

#33 Add database client logic for webhook transaction log
  database/client.go
  database/database.go
  database/ddl/sqlite/hook.go
  database/dml/dml_test.go
  database/dml/postgres/hook.go
  database/dml/postgres/hook_test.go
  database/dml/postgres/postgres_test.go
  database/dml/postgres_test.go
  database/dml/sqlite/hook.go
  database/dml/sqlite/hook_test.go
  database/dml/sqlite/sqlite_test.go
  database/dml/sqlite_test.go
  database/hook.go
  database/hook_test.go
  go.mod
  go.sum
Labels: feature

#35 Add disclaimer
  .github/README.md
Labels: enhancement

#38 Add endpoints for webhook transaction log
  api/hook.go
  router/build.go
  router/hook.go
  router/repo.go
  router/router.go
  source/github/repo.go
Labels: feature

#37 Add the ability to route builds
  api/webhook.go
  cmd/server/main.go
  cmd/server/queue.go
  docker-compose.yml
  go.mod
  go.sum
  queue/queue.go
  queue/redis/route.go
  queue/redis/route_test.go
Labels: feature

#39 Add handlers for webhook transaction log
  api/hook.go
  api/step.go
  database/database.go
  database/dml/postgres/hook.go
  database/dml/sqlite/hook.go
  database/hook.go
  database/hook_test.go
Labels: feature

#40 Create webhook transaction log
  api/build.go
  api/webhook.go
  source/github/webhook.go
  source/github/webhook_test.go
  source/source.go
Labels: feature

#41 Leave admin status after subsequent logins
  api/authentication.go
Labels: feature

#43 fix(stages): use step id for a stages build
  api/step.go
Labels: bug

#42 Add killed, failure, success totals for metrics
  api/metrics.go
Labels: enhancement

#44 Refactor changeset logic
  api/build.go
  api/webhook.go
  source/github/changeset.go
  source/github/changeset_test.go
  source/github/repo.go
  source/github/repo_test.go
  source/source.go
Labels: enhancement

#46 Allow ability to remove resources
  database/build.go
  database/dml/postgres/build.go
  database/dml/postgres/hook.go
  database/dml/postgres/log.go
  database/dml/postgres/repo.go
  database/dml/postgres/secret.go
  database/dml/postgres/service.go
  database/dml/postgres/step.go
  database/dml/postgres/user.go
  database/dml/sqlite/build.go
  database/dml/sqlite/hook.go
  database/dml/sqlite/log.go
  database/dml/sqlite/repo.go
  database/dml/sqlite/secret.go
  database/dml/sqlite/service.go
  database/dml/sqlite/step.go
  database/dml/sqlite/user.go
  database/hook.go
  database/log.go
  database/repo.go
  database/secret.go
  database/service.go
  database/step.go
  database/user.go
Labels: bug

#47 Improve error messages set for hooks
  api/webhook.go
Labels: enhancement

#48 Update hook logic for number field
  api/hook.go
  api/webhook.go
  database/database.go
  database/ddl/ddl_test.go
  database/ddl/postgres/hook.go
  database/ddl/postgres/hook_test.go
  database/ddl/postgres/postgres_test.go
  database/ddl/postgres_test.go
  database/ddl/sqlite/hook.go
  database/ddl/sqlite/hook_test.go
  database/ddl/sqlite/sqlite_test.go
  database/ddl/sqlite_test.go
  database/dml/dml_test.go
  database/dml/postgres/hook.go
  database/dml/postgres/hook_test.go
  database/dml/postgres/postgres_test.go
  database/dml/postgres_test.go
  database/dml/sqlite/hook.go
  database/dml/sqlite/hook_test.go
  database/dml/sqlite/sqlite_test.go
  database/dml/sqlite_test.go
  database/hook.go
  database/hook_test.go
  go.mod
  go.sum
  source/github/webhook.go
  source/github/webhook_test.go
Labels: enhancement
