Repository go-vela/server, pull requests merged in 2019-12, with the labels that each got.

#49 Set proper event for webhook transaction log
  source/github/webhook.go
Labels: bug

#52 feat(metrics): add metrics for how many times an image has been used
  api/metrics.go
  database/database.go
  database/dml/dml_test.go
  database/dml/postgres/postgres_test.go
  database/dml/postgres/service.go
  database/dml/postgres/service_test.go
  database/dml/postgres/step.go
  database/dml/postgres/step_test.go
  database/dml/postgres_test.go
  database/dml/sqlite/service.go
  database/dml/sqlite/service_test.go
  database/dml/sqlite/sqlite_test.go
  database/dml/sqlite/step.go
  database/dml/sqlite/step_test.go
  database/dml/sqlite_test.go
  database/service.go
  database/service_test.go
  database/step.go
  database/step_test.go
Labels: enhancement

#53 Add logic to handle init stage/step
  go.mod
  go.sum
Labels: feature

#54 Uptick version for new release
  router/middleware/header_test.go
  version/version.go
Labels: bug

#55 Release v0.2.0-rc2
  go.mod
  go.sum
Labels: enhancement

#56 feat(metrics): export metrics for the count of each step status
  api/metrics.go
  database/database.go
  database/dml/dml_test.go
  database/dml/postgres/postgres_test.go
  database/dml/postgres/step.go
  database/dml/postgres/step_test.go
  database/dml/postgres_test.go
  database/dml/sqlite/sqlite_test.go
  database/dml/sqlite/step.go
  database/dml/sqlite/step_test.go
  database/dml/sqlite_test.go
  database/step.go
  database/step_test.go
Labels: enhancement

#59 chore: update all go mod dependencies
  go.mod
  go.sum
Labels: enhancement

#60 feat: add extra metadata for compiler
  api/build.go
  api/webhook.go
  cmd/server/metadata.go
  cmd/server/server.go
  database/init.go
  go.mod
  go.sum
  router/middleware/metadata.go
  router/middleware/metadata_test.go
Labels: feature

#61 feat(build): add email and link fields
  database/build_test.go
  database/ddl/postgres/build.go
  database/ddl/sqlite/build.go
  go.mod
  go.sum
  router/middleware/build/build_test.go
Labels: feature

#62 improvement: populating build fields
  api/build.go
  api/webhook.go
  source/github/webhook.go
  source/github/webhook_test.go
Labels: enhancement

#63 chore: update go-vela dependencies
  go.mod
  go.sum
Labels: enhancement

#64 fix(badge): establish repo before using it
  router/router.go
Labels: bug

#65 ci: switch from coveralls to codecov
  .github/README.md
  .github/workflows/test.yml
Labels: enhancement

#66 ci: add explicit configuration for automation
  .golangci.yml
  codecov.yml
Labels: enhancement

#67 fix(secrets): default allow command to true
  api/secret.go
Labels: bug

#68 chore: update for v0.2.0
  go.mod
  go.sum
Labels: dependencies

#69 ci(linters): update funlen linter settings
  .golangci.yml
Labels: enhancement
