Repository go-vela/server, pull requests merged in 2020-11, with the labels that each got.

#208 fix: set repo fields off input provided
  api/repo.go
Labels: bug

#212 feat: encrypt native secret values
  cmd/vela-server/main.go
  cmd/vela-server/secret.go
  cmd/vela-server/validate.go
  docker-compose.yml
  router/middleware/secret_test.go
  secret/context_test.go
  secret/native/count_test.go
  secret/native/create.go
  secret/native/create_test.go
  secret/native/crypto.go
  secret/native/crypto_test.go
  secret/native/delete_test.go
  secret/native/get.go
  secret/native/get_test.go
  secret/native/list.go
  secret/native/list_test.go
  secret/native/native.go
  secret/native/native_test.go
  secret/native/update.go
  secret/native/update_test.go
Labels: feature

#214 refactor: secrets.env -> .env for consistency
  .env.example
  .gitignore
  DOCS.md
  docker-compose.yml
Labels: enhancement

#216 fix: add encoding component
  secret/native/crypto.go
Labels: enhancement
