Repository go-vela/server, pull requests merged in 2020-05, with the labels that each got.

#145 feat: support deployment target
  go.mod
  go.sum
Labels: feature

#146 chore: update dependencies to v0.4.0
  go.mod
  go.sum
Labels: dependencies

#150 chore: update dependencies for release
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: dependencies

#152 chore: update for patch release v0.4.2
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: dependencies

#153 chore: update for patch release v0.4.3
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: dependencies

#156 docs: divert bugs and features to community
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
Labels: enhancement
