Repository go-vela/server, pull requests merged in 2020-09, with the labels that each got.

#179 fix(api): setting active flag for repo
  api/repo.go
Labels: bug

#180 feat(metrics): support collecting service statuses
  api/metrics.go
  database/database.go
  database/dml/dml_test.go
  database/dml/postgres/postgres_test.go
  database/dml/postgres/service.go
  database/dml/postgres/service_test.go
  database/dml/postgres_test.go
  database/dml/sqlite/service.go
  database/dml/sqlite/service_test.go
  database/dml/sqlite/sqlite_test.go
  database/dml/sqlite_test.go
  database/service.go
  database/service_test.go
Labels: feature

#184 release: updates for v0.6.0-rc1
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: dependencies

#186 fix: webhook race condition on build creation
  api/build.go
  api/webhook.go
Labels: bug

#188 release: updates for v0.6.0-rc2
  go.mod
  go.sum
Labels: dependencies

#189 release: updates for v0.6.0
  go.mod
  go.sum
Labels: dependencies
