Repository go-vela/server, pull requests merged in 2020-10, with the labels that each got.

#191 fix: webhook race condition on build creation v2
  api/webhook.go
Labels: bug

#190 feat(vault): add logic to obtain/refresh token with aws auth method
  cmd/vela-server/main.go
  cmd/vela-server/secret.go
  cmd/vela-server/validate.go
  go.mod
  go.sum
  secret/vault/count_test.go
  secret/vault/create_test.go
  secret/vault/delete_test.go
  secret/vault/get_test.go
  secret/vault/list_test.go
  secret/vault/refresh.go
  secret/vault/refresh_test.go
  secret/vault/testdata/refresh/auth-response-error-nil-secret.json
  secret/vault/testdata/refresh/auth-response-error-no-auth-values.json
  secret/vault/testdata/refresh/auth-response-error-role-not-found.json
  secret/vault/testdata/refresh/auth-response-success.json
  secret/vault/testdata/refresh/metadata-response-1.json
  secret/vault/testdata/refresh/secret-response-1.json
  secret/vault/testdata/refresh/secret-response-error-not-found.json
  secret/vault/update_test.go
  secret/vault/vault.go
  secret/vault/vault_test.go
Labels: feature

#192 fix(vault): skip auth method if token is provided
  cmd/vela-server/validate.go
Labels: bug

#194 fix(open-api): Correct OpenAPI(swagger) issues
  api-spec/vela-server-v0.6.1.json
  api/admin/build.go
  api/admin/hook.go
  api/admin/repo.go
  api/admin/secret.go
  api/admin/service.go
  api/admin/step.go
  api/admin/user.go
  api/build.go
  api/deployment.go
  api/hook.go
  api/log.go
  api/repo.go
  api/secret.go
  api/service.go
  router/router.go
Labels: hacktoberfest-accepted

#195 enhance!: change whitelist to allowlist
  api/repo.go
  cmd/vela-server/main.go
  cmd/vela-server/server.go
  router/middleware/allowlist.go
  router/middleware/allowlist_test.go
Labels: enhancement

#198 Missed some swagger changes
  api-spec/vela-server-v0.6.1.json
  api/admin/secret.go
  api/admin/service.go
  api/admin/step.go
  api/step.go
  api/user.go
Labels: enhancement

#196 feat: use new version pkg
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  Makefile
  api/version.go
  cmd/vela-server/main.go
  go.mod
  go.sum
  router/middleware/header.go
  router/middleware/header_test.go
  version/version.go
Labels: enhancement, feature

#201 fix: add fetch depth for tag history
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
Labels: bug

#200 enhancement: pull repo info during repo creation
  api/repo.go
  source/github/repo.go
  source/github/repo_test.go
  source/github/testdata/get_repo.json
  source/source.go
Labels: enhancement

#204 docs: update info for local development
  .github/CONTRIBUTING.md
  .github/DOCS.md
  .github/README.md
  .github/SUPPORT.md
  DOCS.md
  docker-compose.yml
  secrets.env.example
Labels: enhancement
