Repository go-vela/server, pull requests merged in 2020-01, with the labels that each got.

#76 chore: use full apache license
  LICENSE
Labels: enhancement

#79 feat: add version handler
  api/version.go
  router/router.go
Labels: feature

#80 fix: update list actions to include pagination
  source/github/access.go
  source/github/changeset.go
Labels: bug

#81 fix: update dependencies for compiler
  go.mod
  go.sum
Labels: dependencies

#82 feat: add Hash field for Repo type
  database/ddl/postgres/repo.go
  database/ddl/sqlite/repo.go
  database/repo_test.go
  go.mod
  go.sum
  router/middleware/build/build_test.go
  router/middleware/perm/perm_test.go
  router/middleware/repo/repo_test.go
  router/middleware/service/service_test.go
  router/middleware/step/step_test.go
Labels: feature
