Repository go-vela/server, pull requests merged in 2020-02, with the labels that each got.

#85 feat: add logic to create repo hash
  api/authenticate.go
  api/login.go
  api/repo.go
Labels: feature

#90 feat: add secret for webhooks
  api/repo.go
  source/github/repo.go
  source/github/repo_test.go
  source/source.go
Labels: feature

#91 feat: verify webhook repo secret
  api/webhook.go
  source/github/webhook.go
  source/github/webhook_test.go
  source/source.go
Labels: feature

#92 feat: add admin services endpoint
  api/admin/service.go
  router/admin.go
Labels: feature

#93 feat: add admin hooks endpoint
  api/admin/hook.go
  router/admin.go
Labels: feature

#94 fix: typos in documentation
  api/admin/service.go
  router/admin.go
Labels: enhancement

#97 chore: update go-vela dependencies
  go.mod
  go.sum
Labels: dependencies

#98 fix: duplicate gin.Context for webhook validation
  api/webhook.go
Labels: bug

#99 chore: update go-github to v29
  go.mod
  go.sum
  source/github/access.go
  source/github/changeset.go
  source/github/github.go
  source/github/github_test.go
  source/github/repo.go
  source/github/webhook.go
Labels: dependencies

#100 feat(source): add trace level logging
  source/github/access.go
  source/github/authentication.go
  source/github/changeset.go
  source/github/repo.go
  source/github/webhook.go
Labels: feature

#101 fix: duplicate http.Request for webhook validation
  api/webhook.go
Labels: bug

#102 improvement: trim whitespace for hashes
  api/authenticate.go
  api/repo.go
Labels: enhancement

#104 fix: hash used for webhook secret
  api/repo.go
Labels: bug

#105 feat: allow platform admins to update resources
  api/admin/build.go
  api/admin/hook.go
  api/admin/repo.go
  api/admin/secret.go
  api/admin/service.go
  api/admin/step.go
  api/admin/user.go
  router/admin.go
Labels: feature

#106 enhancement(badge): add ability to target branch
  api/badge.go
  database/build.go
  database/build_test.go
  database/database.go
  database/dml/dml_test.go
  database/dml/postgres/build.go
  database/dml/postgres/build_test.go
  database/dml/postgres/postgres_test.go
  database/dml/postgres_test.go
  database/dml/sqlite/build.go
  database/dml/sqlite/build_test.go
  database/dml/sqlite/sqlite_test.go
  database/dml/sqlite_test.go
  go.mod
  go.sum
  router/router.go
Labels: enhancement

#107 chore: updates for v0.3.0-rc3
  go.mod
  go.sum
Labels: dependencies

#109 update deps for v0.3.0
  go.mod
  go.sum
Labels: dependencies
