Repository go-vela/server, pull requests merged in 2020-04, with the labels that each got.

#125 fix(webhook): set proper error message
  api/webhook.go
Labels: bug

#128 feat: add worker information to Service
  database/ddl/postgres/service.go
  database/ddl/sqlite/service.go
  database/service_test.go
  go.mod
  go.sum
  router/middleware/service/service_test.go
Labels: feature

#129 chore: update for v0.4.0-rc1
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: dependencies

#130 refactor(source): use TrimPrefix() over Replace()
  source/github/webhook.go
Labels: enhancement

#131 feat: add deployment shell
  api/admin/deployment.go
  api/deployment.go
  router/admin.go
  router/deployment.go
  router/router.go
Labels: feature

#133 feat(source): support deployment webhooks
  source/github/testdata/deployment.json
  source/github/testdata/deployment_commit.json
  source/github/webhook.go
  source/github/webhook_test.go
Labels: feature

#135 refactor(source): move testdata webhooks
  source/github/testdata/hooks/deployment.json
  source/github/testdata/hooks/deployment_commit.json
  source/github/testdata/hooks/issue_comment.json
  source/github/testdata/hooks/pull_request.json
  source/github/testdata/hooks/pull_request_closed_action.json
  source/github/testdata/hooks/pull_request_closed_state.json
  source/github/testdata/hooks/push.json
  source/github/testdata/hooks/push_no_sender.json
  source/github/webhook_test.go
Labels: enhancement

#138 feat(source): support github deployments
  go.mod
  go.sum
  source/github/deployment.go
  source/github/deployment_test.go
  source/github/repo.go
  source/github/testdata/deployment.json
  source/github/testdata/deployments.json
  source/source.go
Labels: feature

#139 chore: update dependencies for v0.4.0-rc2
  go.mod
  go.sum
Labels: dependencies

#140 refactor(deployments): remove unsupported endpoints
  api/deployment.go
  router/deployment.go
Labels: enhancement

#141 chore: update version to v0.4.0-rc3
  go.mod
  go.sum
Labels: dependencies

#142 feat(source): add func to count deployments
  source/github/deployment.go
  source/github/deployment_test.go
  source/github/testdata/deployments.json
  source/source.go
Labels: feature

#143 feat(api): add deployment endpoints
  api/deployment.go
  router/deployment.go
Labels: feature

#144 refactor(api): use full word for deployment
  api/deployment.go
Labels: enhancement
