Repository go-vela/server, pull requests merged in 2020-07, with the labels that each got.

#164 enhancement(routes): add which route was selected for build
  api/webhook.go
Labels: enhancement

#167 feat(source): set build status for deployments
  source/github/repo.go
  source/github/repo_test.go
Labels: feature

#168 fix(postgres): update favorites column in user table to 5000
  database/ddl/postgres/user.go
Labels: bug

#169 feat(skip): add check to determine if hook should be skipped
  api/webhook.go
  go.mod
  go.sum
Labels: feature

#171 chore: update go mod for v0.5.0-rc1
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: dependencies
