Repository go-vela/server, pull requests merged in 2021-02, with the labels that each got.

#269 chore: update go-vela/compiler on v0.7.0-rc4
  go.mod
  go.sum
Labels: dependencies

#273 chore: upgrade go-vela deps on v0.7.0
  go.mod
  go.sum
Labels: dependencies

#274 revert: removing secret encryption functionality
  secret/native/create.go
  secret/native/create_test.go
  secret/native/get.go
  secret/native/get_test.go
  secret/native/list.go
  secret/native/list_test.go
  secret/native/update.go
Labels: bug

#275 fix(source): processing deployments with empty payloads
  source/github/deployment.go
  source/github/webhook.go
Labels: bug

#280 fix: update the server with compiler revert
  api/pipeline.go
  go.mod
  go.sum
Labels: bug

#285 ci(Makefile): remove pull target from up target
  Makefile
Labels: enhancement

#286 chore: linter fixes v2
  database/service.go
  database/step.go
  router/middleware/payload.go
  router/middleware/worker.go
  router/middleware/worker/worker.go
Labels: enhancement

#287 feat: set service/step environment after database creation
  api/service.go
  api/step.go
  go.mod
  go.sum
Labels: feature

#291 feat(database): compress logs to reduce storage
  database/log.go
  database/log_test.go
  go.mod
  go.sum
Labels: feature

#294 fix(database): capturing list of logs for a build
  database/log.go
Labels: bug

#298 docs: fix authorization callback url
  DOCS.md
Labels: bug

#301 chore(database): remove unused indexes
  database/ddl/ddl_test.go
  database/ddl/postgres/build.go
  database/ddl/postgres/build_test.go
  database/ddl/postgres/hook.go
  database/ddl/postgres/hook_test.go
  database/ddl/postgres/log.go
  database/ddl/postgres/log_test.go
  database/ddl/postgres/postgres_test.go
  database/ddl/postgres/repo.go
  database/ddl/postgres/repo_test.go
  database/ddl/postgres/secret.go
  database/ddl/postgres/secret_test.go
  database/ddl/postgres/service.go
  database/ddl/postgres/service_test.go
  database/ddl/postgres/step.go
  database/ddl/postgres/step_test.go
  database/ddl/postgres/user.go
  database/ddl/postgres/user_test.go
  database/ddl/postgres_test.go
  database/ddl/sqlite/build.go
  database/ddl/sqlite/build_test.go
  database/ddl/sqlite/hook.go
  database/ddl/sqlite/hook_test.go
  database/ddl/sqlite/log.go
  database/ddl/sqlite/log_test.go
  database/ddl/sqlite/repo.go
  database/ddl/sqlite/repo_test.go
  database/ddl/sqlite/secret.go
  database/ddl/sqlite/secret_test.go
  database/ddl/sqlite/service.go
  database/ddl/sqlite/service_test.go
  database/ddl/sqlite/sqlite_test.go
  database/ddl/sqlite/step.go
  database/ddl/sqlite/step_test.go
  database/ddl/sqlite/user.go
  database/ddl/sqlite/user_test.go
  database/ddl/sqlite_test.go
Labels: enhancement

#297 enhance(database): support setting different compression level
  cmd/vela-server/main.go
  cmd/vela-server/validate.go
  database/client.go
  database/log.go
  go.mod
  go.sum
Labels: enhancement
