Repository go-vela/server, pull requests merged in 2021-05, with the labels that each got.

#356 feat(postgres): add vela resource ddl
  database/postgres/ddl/build.go
  database/postgres/ddl/hook.go
  database/postgres/ddl/log.go
  database/postgres/ddl/repo.go
  database/postgres/ddl/secret.go
  database/postgres/ddl/service.go
  database/postgres/ddl/step.go
  database/postgres/ddl/user.go
  database/postgres/ddl/worker.go
Labels: feature

#357 feat(sqlite): add vela resource ddl
  database/sqlite/ddl/build.go
  database/sqlite/ddl/hook.go
  database/sqlite/ddl/log.go
  database/sqlite/ddl/repo.go
  database/sqlite/ddl/secret.go
  database/sqlite/ddl/service.go
  database/sqlite/ddl/step.go
  database/sqlite/ddl/user.go
  database/sqlite/ddl/worker.go
Labels: feature

#360 feat(postgres): add ClientOpt{} and New() to accept ...ClientOpt{}
  database/postgres/opts.go
  database/postgres/opts_test.go
  database/postgres/postgres.go
  database/postgres/postgres_test.go
  go.mod
  go.sum
Labels: feature

#361 feat(sqlite): add ClientOpt{} and New() to accept ...ClientOpt{}
  database/sqlite/opts.go
  database/sqlite/opts_test.go
  database/sqlite/sqlite.go
  database/sqlite/sqlite_test.go
  go.mod
  go.sum
Labels: feature

#358 feat(postgres): add vela resource dml
  database/postgres/dml/build.go
  database/postgres/dml/hook.go
  database/postgres/dml/log.go
  database/postgres/dml/repo.go
  database/postgres/dml/secret.go
  database/postgres/dml/service.go
  database/postgres/dml/step.go
  database/postgres/dml/user.go
  database/postgres/dml/worker.go
Labels: feature

#363 feat(postgres): add Ping() to verify database connection
  database/postgres/ping.go
  database/postgres/ping_test.go
Labels: feature

#364 feat(sqlite): add Ping() to verify database connection
  database/sqlite/ping.go
  database/sqlite/ping_test.go
Labels: feature

#370 feat(postgres): add user database functions
  database/postgres/user.go
  database/postgres/user_count.go
  database/postgres/user_count_test.go
  database/postgres/user_list.go
  database/postgres/user_list_test.go
  database/postgres/user_test.go
Labels: feature

#371 feat(postgres): add worker database functions
  database/postgres/worker.go
  database/postgres/worker_count.go
  database/postgres/worker_count_test.go
  database/postgres/worker_list.go
  database/postgres/worker_list_test.go
  database/postgres/worker_test.go
Labels: feature

#372 feat(postgres): add hook database functions
  database/postgres/hook.go
  database/postgres/hook_count.go
  database/postgres/hook_count_test.go
  database/postgres/hook_list.go
  database/postgres/hook_list_test.go
  database/postgres/hook_test.go
Labels: feature

#373 feat(postgres): add build database functions
  database/postgres/build.go
  database/postgres/build_count.go
  database/postgres/build_count_test.go
  database/postgres/build_list.go
  database/postgres/build_list_test.go
  database/postgres/build_test.go
Labels: feature

#374 feat(postgres): add secret database functions
  database/postgres/secret.go
  database/postgres/secret_count.go
  database/postgres/secret_count_test.go
  database/postgres/secret_list.go
  database/postgres/secret_list_test.go
  database/postgres/secret_test.go
Labels: feature

#375 feat(postgres): add log database functions
  database/postgres/log.go
  database/postgres/log_test.go
Labels: feature

#376 feat(postgres): add step database functions
  database/postgres/step.go
  database/postgres/step_count.go
  database/postgres/step_count_test.go
  database/postgres/step_list.go
  database/postgres/step_list_test.go
  database/postgres/step_test.go
Labels: feature

#377 feat(postgres): add service database functions
  database/postgres/service.go
  database/postgres/service_count.go
  database/postgres/service_count_test.go
  database/postgres/service_list.go
  database/postgres/service_list_test.go
  database/postgres/service_test.go
Labels: feature

#378 refactor(postgres): update tests with NewTest() returning sql mock
  database/postgres/build_count_test.go
  database/postgres/build_list_test.go
  database/postgres/build_test.go
  database/postgres/hook_count_test.go
  database/postgres/hook_list_test.go
  database/postgres/hook_test.go
  database/postgres/log_test.go
  database/postgres/ping_test.go
  database/postgres/postgres.go
  database/postgres/repo_count_test.go
  database/postgres/repo_list_test.go
  database/postgres/repo_test.go
  database/postgres/secret_count_test.go
  database/postgres/secret_list_test.go
  database/postgres/secret_test.go
  database/postgres/service_count_test.go
  database/postgres/service_list_test.go
  database/postgres/service_test.go
  database/postgres/step_count_test.go
  database/postgres/step_list_test.go
  database/postgres/step_test.go
  database/postgres/user_count_test.go
  database/postgres/user_list_test.go
  database/postgres/user_test.go
  database/postgres/worker_count_test.go
  database/postgres/worker_list_test.go
  database/postgres/worker_test.go
Labels: enhancement

#380 fix(sqlite): DML query placeholders for parameters
  database/sqlite/dml/build.go
  database/sqlite/dml/worker.go
  database/sqlite/sqlite.go
Labels: bug

#395 feat(postgres): add setupDatabase() to setup database connections
  database/postgres/postgres.go
  database/postgres/postgres_test.go
Labels: feature

#382 feat(sqlite): add user database functions
  database/sqlite/user.go
  database/sqlite/user_count.go
  database/sqlite/user_count_test.go
  database/sqlite/user_list.go
  database/sqlite/user_list_test.go
  database/sqlite/user_test.go
Labels: feature

#396 feat(postgres): add createTables() to create database tables
  database/postgres/postgres.go
  database/postgres/postgres_test.go
Labels: feature

#392 fix(postgres): DML query placeholders for parameters
  database/postgres/build_count_test.go
  database/postgres/build_list_test.go
  database/postgres/build_test.go
  database/postgres/dml/build.go
  database/postgres/dml/hook.go
  database/postgres/dml/log.go
  database/postgres/dml/repo.go
  database/postgres/dml/secret.go
  database/postgres/dml/service.go
  database/postgres/dml/step.go
  database/postgres/dml/user.go
  database/postgres/dml/worker.go
  database/postgres/hook_count_test.go
  database/postgres/hook_list_test.go
  database/postgres/hook_test.go
  database/postgres/log_test.go
  database/postgres/repo_count_test.go
  database/postgres/repo_list_test.go
  database/postgres/repo_test.go
  database/postgres/secret_count_test.go
  database/postgres/secret_list_test.go
  database/postgres/secret_test.go
  database/postgres/service_count_test.go
  database/postgres/service_list_test.go
  database/postgres/service_test.go
  database/postgres/step_count_test.go
  database/postgres/step_list_test.go
  database/postgres/step_test.go
  database/postgres/user_count_test.go
  database/postgres/user_list_test.go
  database/postgres/user_test.go
  database/postgres/worker_count_test.go
  database/postgres/worker_list_test.go
  database/postgres/worker_test.go
  go.mod
  go.sum
Labels: bug

#397 feat(postgres): add createIndexes() to create database indexes
  database/postgres/postgres.go
  database/postgres/postgres_test.go
Labels: feature

#398 refactor(database)!: switch to use postgres.New()
  api/build.go
  cmd/vela-server/database.go
  database/build.go
  database/build_test.go
  database/database.go
Labels: enhancement

#393 feat(repo): use repo counter as source for build number
  api/build.go
  api/repo.go
  api/webhook.go
  database/ddl/postgres/repo.go
  database/ddl/sqlite/repo.go
  database/postgres/ddl/repo.go
  database/postgres/repo_list_test.go
  database/postgres/repo_test.go
  database/repo_test.go
  database/sqlite/ddl/repo.go
  go.mod
  go.sum
  router/middleware/repo/repo_test.go
Labels: feature

#394 deps(compiler): allow templates to export secrets
  api/pipeline.go
  docker-compose.yml
  go.mod
  go.sum
  router/middleware/compiler.go
Labels: dependencies

#399 fix(postgres): call setupDatabase() helper in New()
  database/postgres/postgres.go
Labels: bug

#381 feat(sqlite): add repo database functions
  database/sqlite/repo.go
  database/sqlite/repo_count.go
  database/sqlite/repo_count_test.go
  database/sqlite/repo_list.go
  database/sqlite/repo_list_test.go
  database/sqlite/repo_test.go
  database/sqlite/user_list.go
Labels: feature

#383 feat(sqlite): add worker database functions
  database/sqlite/worker.go
  database/sqlite/worker_count.go
  database/sqlite/worker_count_test.go
  database/sqlite/worker_list.go
  database/sqlite/worker_list_test.go
  database/sqlite/worker_test.go
Labels: feature

#384 feat(sqlite): add hook database functions
  database/sqlite/hook.go
  database/sqlite/hook_count.go
  database/sqlite/hook_count_test.go
  database/sqlite/hook_list.go
  database/sqlite/hook_list_test.go
  database/sqlite/hook_test.go
Labels: feature

#386 feat(sqlite): add secret database functions
  database/sqlite/secret.go
  database/sqlite/secret_count.go
  database/sqlite/secret_count_test.go
  database/sqlite/secret_list.go
  database/sqlite/secret_list_test.go
  database/sqlite/secret_test.go
Labels: feature

#401 refactor(spec): build spec as part of release
  .github/workflows/spec.yml
  Makefile
  api-spec/vela-server.json
  router/router.go
Labels: enhancement

#385 feat(sqlite): add build database functions
  database/sqlite/build.go
  database/sqlite/build_count.go
  database/sqlite/build_count_test.go
  database/sqlite/build_list.go
  database/sqlite/build_list_test.go
  database/sqlite/build_test.go
Labels: feature

#387 feat(sqlite): add service database functions
  database/sqlite/service.go
  database/sqlite/service_count.go
  database/sqlite/service_count_test.go
  database/sqlite/service_list.go
  database/sqlite/service_list_test.go
  database/sqlite/service_test.go
Labels: feature

#388 feat(sqlite): add step database functions
  database/sqlite/step.go
  database/sqlite/step_count.go
  database/sqlite/step_count_test.go
  database/sqlite/step_list.go
  database/sqlite/step_list_test.go
  database/sqlite/step_test.go
Labels: feature

#389 feat(sqlite): add log database functions
  database/sqlite/log.go
  database/sqlite/log_test.go
Labels: feature

#403 chore: upgrade go-vela/pkg-queue on v0.8.0-rc1
  go.mod
  go.sum
Labels: dependencies

#405 feat(sqlite): add setupDatabase() to setup connections
  database/sqlite/sqlite.go
  database/sqlite/sqlite_test.go
Labels: feature

#406 feat(sqlite): add createTables() to create database tables
  database/sqlite/build_test.go
  database/sqlite/hook_test.go
  database/sqlite/log_test.go
  database/sqlite/secret_test.go
  database/sqlite/service_test.go
  database/sqlite/sqlite.go
  database/sqlite/sqlite_test.go
  database/sqlite/step_test.go
  database/sqlite/user_test.go
  database/sqlite/worker_test.go
Labels: feature

#407 feat(sqlite): add createIndexes() to create database indexes
  database/sqlite/sqlite.go
  database/sqlite/sqlite_test.go
Labels: feature

#409 fix(postgres): add workaround for gorm record not found
  database/postgres/build.go
  database/postgres/build_test.go
  database/postgres/hook.go
  database/postgres/hook_test.go
  database/postgres/log.go
  database/postgres/log_test.go
  database/postgres/repo.go
  database/postgres/repo_test.go
  database/postgres/secret.go
  database/postgres/secret_test.go
  database/postgres/service.go
  database/postgres/service_test.go
  database/postgres/step.go
  database/postgres/step_test.go
  database/postgres/user.go
  database/postgres/user_test.go
  database/postgres/worker.go
  database/postgres/worker_test.go
Labels: bug

#410 fix(sqlite): add workaround for gorm record not found
  database/sqlite/build.go
  database/sqlite/build_test.go
  database/sqlite/hook.go
  database/sqlite/hook_test.go
  database/sqlite/log.go
  database/sqlite/log_test.go
  database/sqlite/repo.go
  database/sqlite/repo_test.go
  database/sqlite/secret.go
  database/sqlite/secret_test.go
  database/sqlite/service.go
  database/sqlite/service_test.go
  database/sqlite/step.go
  database/sqlite/step_test.go
  database/sqlite/user.go
  database/sqlite/user_test.go
  database/sqlite/worker.go
  database/sqlite/worker_test.go
Labels: bug

#411 refactor(database)!: switch to use sqlite.New()
  cmd/vela-server/database.go
Labels: enhancement

#414 chore: upgrade go-vela deps on v0.8.0-rc2
  go.mod
  go.sum
Labels: dependencies
