Repository go-vela/server, pull requests merged in 2021-08, with the labels that each got.

#455 feat(database): support skipping creation of tables and indexes
  cmd/vela-server/database.go
  database/database_test.go
  database/flags.go
  database/postgres/opts.go
  database/postgres/opts_test.go
  database/postgres/postgres.go
  database/postgres/postgres_test.go
  database/setup.go
  database/setup_test.go
  database/sqlite/opts.go
  database/sqlite/opts_test.go
  database/sqlite/sqlite.go
  database/sqlite/sqlite_test.go
Labels: feature

#460 fix(deps): address vulnerable jwt-go library
  go.mod
  go.sum
  router/middleware/token/token.go
  router/middleware/token/token_test.go
Labels: bug, dependencies

#463 fix: correct build number on restart
  api/build.go
Labels: bug

#464 fix(database): sort org build list by started timestamp
  database/postgres/build_list.go
  database/postgres/build_list_test.go
  database/sqlite/build_list.go
  database/sqlite/build_list_test.go
Labels: bug

#469 fix(database): sort by created instead of started
  database/postgres/build_list.go
  database/postgres/build_list_test.go
  database/sqlite/build_list.go
Labels: enhancement

#470 fix: add second order to ensure order consistency
  database/postgres/build_list.go
  database/postgres/build_list_test.go
  database/sqlite/build_list.go
Labels: enhancement
