Repository go-vela/server, pull requests merged in 2021-04, with the labels that each got.

#321 feat(database): encrypt repo fields for enhanced security
  database/repo.go
Labels: feature

#327 feat: add source.Driver() function
  source/github/driver.go
  source/github/driver_test.go
  source/service.go
Labels: feature

#328 feat: add secret.Driver() function
  secret/native/driver.go
  secret/native/driver_test.go
  secret/service.go
  secret/vault/driver.go
  secret/vault/driver_test.go
Labels: feature

#331 refactor: switch to using go-vela/pkg-queue
  api/build.go
  api/webhook.go
  cmd/vela-server/main.go
  cmd/vela-server/queue.go
  cmd/vela-server/validate.go
  docker-compose.yml
  go.mod
  go.sum
  queue/context.go
  queue/doc.go
  queue/queue.go
  queue/redis/doc.go
  queue/redis/publish.go
  queue/redis/redis.go
  queue/redis/route.go
  queue/redis/route_test.go
  router/middleware/queue.go
  router/middleware/queue_test.go
Labels: dependencies

#337 fix: add check for token
  go.mod
  go.sum
  source/github/authentication.go
  source/github/authentication_test.go
Labels: bug

#338 chore: bump github lib to latest
  source/github/authentication.go
Labels: dependencies

#336 refactor: switch to using secret.New()
  cmd/vela-server/main.go
  cmd/vela-server/secret.go
  docker-compose.yml
  secret/flags.go
  secret/secret_test.go
  secret/setup.go
  secret/setup_test.go
Labels: enhancement

#333 refactor!: switch to using source.New()
  .env.example
  cmd/vela-server/main.go
  cmd/vela-server/source.go
  docker-compose.yml
  source/flags.go
  source/setup.go
  source/setup_test.go
  source/source_test.go
Labels: enhancement

#345 fix: creating server metadata from flags
  cmd/vela-server/metadata.go
Labels: bug

#347 feat: use BuildQueue{} from go-vela/types
  database/build.go
  database/database.go
  go.mod
  go.sum
Labels: feature

#349 chore: update go-vela/types to latest
  go.mod
  go.sum
Labels: dependencies

#341 feat(database): add postgres package shell
  database/postgres/ddl/doc.go
  database/postgres/dml/doc.go
  database/postgres/doc.go
Labels: feature

#342 feat(database): add sqlite package shell
  database/sqlite/ddl/doc.go
  database/sqlite/dml/doc.go
  database/sqlite/doc.go
Labels: feature

#352 fix(api): enable updating build enqueued field
  api/build.go
Labels: bug
