Repository go-vela/server, pull requests merged in 2021-01, with the labels that each got.

#218 feat(repo settings): add build timeout default 30 minutes
  api/repo.go
  go.mod
  go.sum
Labels: feature

#170 feat(token): change to use expiring tokens
  api/authenticate.go
  api/login.go
  api/logout.go
  api/token.go
  api/user.go
  cmd/vela-server/main.go
  cmd/vela-server/metadata.go
  cmd/vela-server/server.go
  cmd/vela-server/validate.go
  database/database.go
  database/ddl/ddl_test.go
  database/ddl/postgres/postgres_test.go
  database/ddl/postgres/user.go
  database/ddl/postgres/user_test.go
  database/ddl/postgres_test.go
  database/ddl/sqlite/sqlite_test.go
  database/ddl/sqlite/user.go
  database/ddl/sqlite/user_test.go
  database/ddl/sqlite_test.go
  database/dml/dml_test.go
  database/dml/postgres/postgres_test.go
  database/dml/postgres/user.go
  database/dml/postgres/user_test.go
  database/dml/postgres_test.go
  database/dml/sqlite/sqlite_test.go
  database/dml/sqlite/user.go
  database/dml/sqlite/user_test.go
  database/dml/sqlite_test.go
  database/user.go
  database/user_test.go
  docker-compose.yml
  go.mod
  go.sum
  router/middleware/header.go
  router/middleware/header_test.go
  router/middleware/perm/perm.go
  router/middleware/perm/perm_test.go
  router/middleware/secure_cookie.go
  router/middleware/secure_cookie_test.go
  router/middleware/token/token.go
  router/middleware/token/token_test.go
  router/middleware/user/user.go
  router/middleware/user/user_test.go
  router/router.go
  source/github/authentication.go
  source/github/github.go
  source/github/github_test.go
  source/source.go
Labels: feature

#252 chore(deps): upgrade go-vela deps on v0.7.0-rc2
  go.mod
  go.sum
Labels: dependencies

#256 fix(webhook): duplicate compiler before processing
  api/webhook.go
  go.mod
  go.sum
Labels: bug

#258 refactor: add API port back to server
  cmd/vela-server/main.go
  cmd/vela-server/server.go
Labels: enhancement
