Repository go-vela/server, pull requests merged in 2021-07, with the labels that each got.

#436 enhance: support .env files
  cmd/vela-server/main.go
  go.mod
  go.sum
Labels: dependencies, enhancement

#439 feat(database): support configuration from file paths
  database/flags.go
Labels: feature

#441 feat(source): support configuration from file paths
  source/flags.go
Labels: feature

#440 feat(secret): support configuration from file paths
  secret/flags.go
Labels: feature

#450 fix(deployments): add deployment payload to getters
  api/build_test.go
  database/postgres/build_test.go
  database/postgres/hook_test.go
  database/postgres/repo_test.go
  database/postgres/service_test.go
  database/postgres/step_test.go
  go.mod
  go.sum
  source/github/deployment.go
  source/github/deployment_test.go
  source/github/testdata/deployments.json
Labels: enhancement

#443 enhance(api): support querying builds by branch/status
  api/build.go
  database/postgres/build_count.go
  database/postgres/build_count_test.go
  database/postgres/build_list.go
  database/postgres/build_list_test.go
  database/postgres/dml/build.go
  database/service.go
  database/sqlite/build_count.go
  database/sqlite/build_count_test.go
  database/sqlite/build_list.go
  database/sqlite/build_list_test.go
  database/sqlite/dml/build.go
Labels: enhancement
