Repository go-vela/server, pull requests merged in 2022-03, with the labels that each got.

#599 fixing whitespace secret bug
  api/secret.go
Labels: bug

#594 refactor: docs for local setup
  .env.example
  DOCS.md
  docker-compose.yml
Labels: enhancement

#608 enhance: add local template support for CompileLite()
  api/pipeline.go
  compiler/engine.go
  compiler/native/compile.go
  compiler/native/compile_test.go
Labels: enhancement

#574 feat(database): add support for pipelines
  database/pipeline/count.go
  database/pipeline/count_repo.go
  database/pipeline/count_repo_test.go
  database/pipeline/count_test.go
  database/pipeline/create.go
  database/pipeline/create_test.go
  database/pipeline/delete.go
  database/pipeline/delete_test.go
  database/pipeline/get.go
  database/pipeline/get_repo.go
  database/pipeline/get_repo_test.go
  database/pipeline/get_test.go
  database/pipeline/index.go
  database/pipeline/index_test.go
  database/pipeline/last_repo.go
  database/pipeline/last_repo_test.go
  database/pipeline/list.go
  database/pipeline/list_repo.go
  database/pipeline/list_repo_test.go
  database/pipeline/list_test.go
  database/pipeline/opts.go
  database/pipeline/opts_test.go
  database/pipeline/pipeline.go
  database/pipeline/pipeline_test.go
  database/pipeline/service.go
  database/pipeline/table.go
  database/pipeline/table_test.go
  database/pipeline/update.go
  database/pipeline/update_test.go
  database/postgres/build_list_test.go
  database/postgres/build_test.go
  database/postgres/ddl/build.go
  database/postgres/ddl/hook.go
  database/postgres/hook_list_test.go
  database/postgres/hook_test.go
  database/postgres/postgres.go
  database/postgres/postgres_test.go
  database/service.go
  database/sqlite/build_test.go
  database/sqlite/ddl/build.go
  database/sqlite/ddl/hook.go
  database/sqlite/hook_count_test.go
  database/sqlite/hook_list_test.go
  database/sqlite/hook_test.go
  database/sqlite/sqlite.go
  go.mod
  go.sum
  router/middleware/build/build_test.go
Labels: feature
