Repository go-vela/server, pull requests merged in 2023-06, with the labels that each got.

#868 feat(database): add agnostic engine
  database/close.go
  database/close_test.go
  database/database.go
  database/database_test.go
  database/driver.go
  database/driver_test.go
  database/validate.go
  database/validate_test.go
Labels: feature

#873 refactor(database): use agnostic engine
  cmd/vela-server/database.go
  cmd/vela-server/server.go
  database/context.go
  database/context_test.go
  database/database.go
  database/database_test.go
  database/flags.go
  database/interface.go
  database/setup.go
  database/setup_test.go
Labels: enhancement

#877 fix(schedules): increment repo counter after read
  cmd/vela-server/schedule.go
Labels: bug

#878 refactor(testing): use database.NewTest()
  database/interface.go
  internal/token/refresh_test.go
  router/middleware/build/build_test.go
  router/middleware/claims/claims_test.go
  router/middleware/database_test.go
  router/middleware/org/org_test.go
  router/middleware/perm/perm_test.go
  router/middleware/pipeline/pipeline_test.go
  router/middleware/repo/repo_test.go
  router/middleware/secret_test.go
  router/middleware/service/service_test.go
  router/middleware/step/step_test.go
  router/middleware/user/user_test.go
  router/middleware/worker/worker_test.go
  secret/context_test.go
  secret/native/count_test.go
  secret/native/create_test.go
  secret/native/delete_test.go
  secret/native/driver_test.go
  secret/native/get_test.go
  secret/native/list_test.go
  secret/native/native_test.go
  secret/native/opts_test.go
  secret/native/update_test.go
  secret/secret_test.go
  secret/setup_test.go
Labels: enhancement

#876 enhance(clone): upgrade target/vela-git to v0.8.0
  cmd/vela-server/main.go
Labels: enhancement

#880 chore(database): remove unused packages
  database/postgres/doc.go
  database/postgres/driver.go
  database/postgres/driver_test.go
  database/postgres/opts.go
  database/postgres/opts_test.go
  database/postgres/ping.go
  database/postgres/ping_test.go
  database/postgres/postgres.go
  database/postgres/postgres_test.go
  database/sqlite/doc.go
  database/sqlite/driver.go
  database/sqlite/driver_test.go
  database/sqlite/opts.go
  database/sqlite/opts_test.go
  database/sqlite/ping.go
  database/sqlite/ping_test.go
  database/sqlite/sqlite.go
  database/sqlite/sqlite_test.go
Labels: enhancement

#888 chore(deps): bulk deps update
  compiler/native/compile_test.go
  compiler/registry/github/github.go
  compiler/registry/github/github_test.go
  compiler/registry/github/template.go
  go.mod
  go.sum
  scm/github/access.go
  scm/github/authentication.go
  scm/github/changeset.go
  scm/github/deployment.go
  scm/github/github.go
  scm/github/github_test.go
  scm/github/repo.go
  scm/github/webhook.go
Labels: dependencies
